### ISSUE TITLE
Style header links for menu list

### ISSUE THREAD

**Issue by kccrtv** [SatcherInstitute/health-equity-tracker#2348]
### Objective:

Apply specific styles to the header links in the menu list to align with the project's design requirements.

### Tasks:

1. **Install DM Sans Font (if not already installed)**
    - Add DM Sans font to the project, if it is not already available.
2. **Global CSS Variables**
    - Define the CSS variables `-383838` and `-0-b-5240` with their corresponding color codes `#383838` and `#0B5240`.
3. **Create Styled Header Link Component**
    - Create a reusable TypeScript component for styled header links, let's call it `StyledHeaderLink.tsx`.
4. **Apply Initial Styles**
    - In `StyledHeaderLink.tsx`, use Material-UI's `makeStyles` or `styled` API to apply the initial styles:
    
    ```css
    color: var(--383838, #383838);
    font-family: DM Sans;
    font-size: 0.875rem;
    font-style: normal;
    font-weight: 500;
    line-height: normal;
    letter-spacing: 0.02625rem;
    
    display: flex;
    padding: 0.25rem 0.5rem 0.25rem 1rem;
    flex-direction: column;
    justify-content: center;
    align-items: flex-start;
    gap: 0.5rem;
    ```
    
5. **Add Hover and Active States**
    - Extend the styles in `StyledHeaderLink.tsx` to include hover and active states with the following styles:
    
    ```css
    '&:hover, &:active': {
      color: var(--0-b-5240, #0B5240);
      font-family: DM Sans;
      font-size: 0.875rem;
      font-style: normal;
      font-weight: 500;
      line-height: normal;
      letter-spacing: 0.02625rem;
    }
    
    ```
    
6. **Implement Event Handlers**
    - Add event handlers such as `onMouseEnter` and `onMouseLeave` to manually control hover states, if necessary.
    
    ```tsx
    onMouseEnter={() => setHover(true)}
    onMouseLeave={() => setHover(false)}
    
    ```
    
    - Also, consider using `onClick` or `onFocus` and `onBlur` for active states.
    
    ```tsx
    onClick={() => setActive(true)}
    onBlur={() => setActive(false)}
    
    ```
    
    1. **Test the Implementation**
        - Manually test to ensure that the hover and active states are functioning as expected.
7. **Integrate into Menu List**
    - Replace current links in the menu list with the newly created `StyledHeaderLink` component.
8. **Quality Assurance**
    - Ensure that the styles are applied correctly in various screen sizes and devices.
    - Verify that the hover and active states work as expected.

---
