### ISSUE TITLE
Nav buttons on mobile

### ISSUE THREAD

**Issue by kccrtv** [SatcherInstitute/health-equity-tracker#2358]
### Issue Description:

Adjust the layout of the navigation buttons to accommodate mobile screen sizes. When the viewport width reaches a mobile breakpoint or smaller, change the flex direction of the buttons' container to column and set the buttons' width to 80vw.

---

### 1. Identify Mobile Breakpoint

- [ ]  Determine the pixel value for the mobile breakpoint where the layout change should occur (e.g., 768px).

### 2. Modify CSS for Button Container (`ButtonContainer.css` or relevant file)

- [ ]  Use media queries to change the `flex-direction` of the button container to `column` when the viewport width is at the mobile breakpoint or smaller.
    
    ```css
    @media (max-width: [Breakpoint]px) {
      .button-container {
        flex-direction: column;
      }
    }
    
    ```
    

### 3. Modify CSS for Individual Buttons (`LeftNavButton.css`, `RightNavButton.css`, or relevant file)

- [ ]  In the same media query, set the width of each button to 80vw.
    
    ```css
    @media (max-width: [Breakpoint]px) {
      .left-nav-button,
      .right-nav-button {
        width: 80vw;
      }
    }
    
    ```
    

### 4. Test the Layout Changes

- [ ]  Test the layout changes in various devices and viewport sizes to ensure it's functioning as expected.

### 5. Update Documentation (if necessary)

- [ ]  Update any relevant documentation to reflect these layout changes for mobile breakpoints.

---

Please replace `[Breakpoint]` with the actual pixel value determined in Task 1. Make sure to adapt the code snippets according to the project's coding standards and architecture.
