### ISSUE TITLE
Create GitHub Action for airflow/dags/cdc_wisqars_youth.py

### ISSUE THREAD

**Issue by benhammondmusic** [SatcherInstitute/health-equity-tracker#4000]
# Goal

Migrate each Airflow DAG to GitHub Actions workflow following established patterns.

## Context

We're moving our data orchestration from Airflow to GitHub Actions. Each DAG needs to be converted to an equivalent GitHub Actions workflow that calls our Cloud Run services.

## Steps

Use the maternal mortality Airflow DAG and existing GitHub Action Workflow as an example pattern to follow:

- [ ] Create a new workflow file at `.github/workflows/dag{ThisDataSource}.yml` for example `dagMaternalMortality.yml`
- [ ] Declare the yaml NAME using the all-caps workflow_id: `name: DAG - THIS_DATA_SOURCE`
- [ ] Set up workflow to run on `workflow_dispatch` (manual trigger)
- [ ] Ensure each DAG `gcs_to_bq_operator` step is recreated calling the `./.github/actions/runSourceToBqPipeline` composite action
  - This action sends a POST request to our `gcs_to_bq_service` which processes source data and stores it as tables in BigQuery
  - Make sure to pass the correct `workflow_id`, `dataset_name`, and `demographic` parameters found in the original Airflow DAG.
- [ ] Ensure each DAG `exporter_operator` step is recreated calling the `./.github/actions/runExportBqToGcsJsonPipeline` composite action
  - This action sends a POST request to our `exporter_service` which exports tables from BigQuery to GCS buckets as NDJSON files
  - Make sure to pass the correct `dataset_name`, `demographic`, and `should_export_as_alls` parameters
- [ ] Maintain the same execution order as in the original DAG. Steps of a GitHub Action job run sequentially by default, so each step will wait on the previous one to complete.

## Example

Original Airflow DAG:

```python
# airflow/dags/maternal_mortality.py
_MM_WORKFLOW_ID = "MATERNAL_MORTALITY_DATA"
_MM_DATASET_NAME = "maternal_mortality_data"
#...
data_ingestion_dag = DAG(
    "maternal_mortality_ingestion_dag",
    default_args=default_args,
    schedule_interval=None,
    description="Ingestion configuration for MATERNAL_MORTALITY",
)
maternal_mortality_bq_payload = util.generate_bq_payload(_MM_WORKFLOW_ID, _MM_DATASET_NAME, demographic="race")
maternal_mortality_bq_operator = util.create_bq_ingest_operator(
    "maternal_mortality_to_bq", maternal_mortality_bq_payload, data_ingestion_dag
)
maternal_mortality_exporter_payload_race = {
    "dataset_name": _MM_DATASET_NAME,
    "demographic": "race",
    "should_export_as_alls": True,
}
maternal_mortality_exporter_operator_race = util.create_exporter_operator(
    "maternal_mortality_exporter_race", maternal_mortality_exporter_payload_race, data_ingestion_dag
)
(maternal_mortality_bq_operator >> maternal_mortality_exporter_operator_race)

```

New GitHub Actions workflow:

```yaml
# .github/workflows/dagMaternalMortality.yml
name: DAG - MATERNAL_MORTALITY_DATA

on:
  workflow_dispatch:

jobs:
  process-maternal-mortality-data:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Process and write race tables to BigQuery
        uses: ./.github/actions/runSourceToBqPipeline
        with:
          workflow_id: "MATERNAL_MORTALITY_DATA"
          dataset_name: "maternal_mortality_data"
          demographic: "race"
          service_url: ${{ secrets.GCS_TO_BQ_SERVICE_URL }}

      - name: Export NDJSON files to GCS buckets from BigQuery tables
        uses: ./.github/actions/runExportBqToGcsJsonPipeline
        with:
          service_url: ${{ secrets.EXPORTER_SERVICE_URL }}
          dataset_name: "maternal_mortality_data"
          demographic: "race"
          should_export_as_alls: "true"

```

## Additional Notes

- These secrets are already available in the repo: `${{ secrets.GCS_TO_BQ_SERVICE_URL }}` and `${{ secrets.EXPORTER_SERVICE_URL }}`
- If you have write access to the repo, you can test by manually triggering the action once it's been merged.
- If you have premissions on your GCP account, you can verify the output in both BigQuery tables and GCS buckets as JSON files.
