### ISSUE TITLE
Refactor handling of prod pipelines

### ISSUE THREAD

**Issue by benhammondmusic** [SatcherInstitute/health-equity-tracker#4078]
# Standardize Pipeline Workflows Between Development and Production Environments

Implement reusable workflows to eliminate duplication between staging and production repositories.

## Implementation Steps

Modify workflow files in the staging repository:

```yaml
name: DAG - MATERNAL_MORTALITY_DATA
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      ref:
        description: 'Branch or tag to checkout'
        type: string
        default: 'main'
env:
  WORKFLOW_ID: "MATERNAL_MORTALITY_DATA"
  DATASET_NAME: "maternal_mortality_data"
  RACE: "race"
jobs:
  trigger-data-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - name: Process and write race tables to BigQuery
        uses: ./.github/actions/runSourceToBqPipeline
        with:
          workflow_id: ${{ env.WORKFLOW_ID }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: ${{ env.RACE }}
          service_url: ${{ secrets.GCS_TO_BQ_SERVICE_URL }}
      - name: Export NDJSON files to GCS buckets from BigQuery tables
        uses: ./.github/actions/runExportBqToGcsJsonPipeline
        with:
          service_url: ${{ secrets.EXPORTER_SERVICE_URL }}
          dataset_name: ${{ env.DATASET_NAME }}
          demographic: ${{ env.RACE }}
          should_export_as_alls: "true"
```

Create caller workflows in the production repository:

```yaml
name: PROD - DAG - MATERNAL_MORTALITY_DATA
on:
  workflow_dispatch:
jobs:
  call-staging-workflow:
    uses: SatcherInstitute/health-equity-tracker/.github/workflows/dagMaternalMortality.yml@main
    with:
      ref: 'release'
    secrets: inherit
```
